# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Region.create([
    { name: 'Акмолинская' },
    { name: 'Актюбинская' },
    { name: 'Алматинская' },
    { name: 'Атырауская' },
    { name: 'ВКО' },
    { name: 'Жамбылская' },
    { name: 'Карагандинская' },
    { name: 'ЗКО' },
    { name: 'Костанайская' },
    { name: 'Кызылординская' },
    { name: 'Мангыстауская' },
    { name: 'Павлодарская' },
    { name: 'СКО' },
    { name: 'Туркестанская' },
    { name: 'ЮКО' },
])

City.create([
    { name: 'Абай', region_id: 7 },
    { name: 'Караганда', region_id: 7 },
    { name: 'Шахтинск', region_id: 7 },
    { name: 'Сарань', region_id: 7 },
    { name: 'Темиртау', region_id: 7 },
    { name: 'Приозерск', region_id: 7 },
    { name: 'Балхаш', region_id: 7 },
    { name: 'Жезказган', region_id: 7 },
    { name: 'Сатпаев', region_id: 7 },
    { name: 'Улытауский', region_id: 7 },
    { name: 'Актогайский', region_id: 7 },
    { name: 'Абайский', region_id: 7 },
    { name: 'Бухар-Жырауский', region_id: 7 },
    { name: 'Жанааркинский', region_id: 7 },
    { name: 'Каражал', region_id: 7 },
    { name: 'Нуринский', region_id: 7 },
    { name: 'Каркаралинский', region_id: 7 },
    { name: 'Осакаровский', region_id: 7 },
    { name: 'Шетский', region_id: 7 },
])

Language.create([
    { name: 'қазақ' },
    { name: 'русский' },
])

Department.create([
    { name: 'МДиГ' },
    { name: 'РАиОТ' },
    { name: 'РМПИ' },
    { name: 'ГРМПИ' },
    { name: 'Механика' },
    { name: 'РЯИК' },
    { name: 'Смит' },
    { name: 'АиД' },
    { name: 'ИЯ' },
    { name: 'ПОиП' },
    { name: 'НТМ' },
    { name: 'ТОМиС' },
    { name: 'ИК' },
    { name: 'ХиХТ' },
    { name: 'ИВС' },
    { name: 'ИТБ' },
    { name: 'ЭС' },
    { name: 'АНК-СГД' },
    { name: 'ФВ' },
    { name: 'ЭМП' },
    { name: 'ИПМ' },
    { name: 'Физика' },
    { name: 'ТСС' },
    { name: 'АПП' },
    { name: 'КИЯК' },
    { name: 'Высшая математика' },
    { name: 'ПТ' },
    { name: 'ТТиЛС' },
    { name: 'ВК' },
    { name: 'Другой источник информации' },
])

Manager.create([
    { name: 'Рымқұлова А.Б.', department_id: 1 },
    { name: 'Цешковская Е.А.', department_id: 2 },
    { name: 'Рабатулы М.Р', department_id: 3 },
    { name: 'Садчиков А.В.', department_id: 4 },
    { name: 'Рахымбаева Г.Ж.', department_id: 5 },
    { name: 'Кишенова А.Ю', department_id: 6 },
    { name: 'Иманов Е.К.', department_id: 7 },
    { name: 'Абдильдина Г.А.', department_id: 8 },
    { name: 'Несипбаева Н.Е.', department_id: 9 },
    { name: 'Омирбекова М', department_id: 10 },
    { name: 'Абдрахманов М.С.', department_id: 11 },
    { name: 'Мусаев М.М.', department_id: 12 },
    { name: 'Ошанов Н.І', department_id: 13 },
    { name: 'Кинаятов М.А.', department_id: 14 },
    { name: 'Сулеймен А.', department_id: 15 },
    { name: 'Кадирова Ж.Б', department_id: 16 },
    { name: 'Магауин Б.К.', department_id: 17 },
    { name: 'Аубакиров Е.Ж', department_id: 18 },
    { name: 'Рахимбеков Б.К.', department_id: 19 },
    { name: 'Лустов Н.', department_id: 20 },
    { name: 'Уәйділдә А.Ө.', department_id: 21 },
    { name: 'Туребаева Г.Б.', department_id: 22 },
    { name: 'Несипова С.С.', department_id: 23 },
    { name: 'Нурмаганбетова Ж.С.', department_id: 24 },
    { name: 'Байпелова Г.С.', department_id: 25 },
    { name: 'Мергембаева А.Ж.', department_id: 26 },
    { name: 'Косбармаков С.Ж.', department_id: 27 },
    { name: 'Жайлаубеков М.А.', department_id: 28 },
    { name: 'Белиспаев Д.Т.', department_id: 29 },
])

EducationForm.create([
    { name: 'дневная' },
    { name: 'дневная сокращенная' },
    { name: 'магистратура' },
    { name: 'докторантура' },
    { name: 'второе высшее' },
    { name: 'дистанционная сокращенная' },
])

EducationProgram.create([
    # бакалавриат
    { name: 'Не определился', education_form_id: 1 },
    { name: 'В004 Подготовка учителей начальной военной подготовки', education_form_id: 1 },
    { name: 'В007 Подготовка учителей художественного труда и черчения', education_form_id: 1 },
    { name: 'В031 Мода, дизайн интерьера и промышленный дизайн', education_form_id: 1 },
    { name: 'В044 Менеджмент и управление', education_form_id: 1 },
    { name: 'В045 Аудит и налогообложение', education_form_id: 1 },
    { name: 'В046 Финансы, экономика, банковское и страховое дело', education_form_id: 1 },
    { name: 'В047 Маркетинг и реклама', education_form_id: 1 },
    { name: 'В050 Биологические и смежные науки', education_form_id: 1 },
    { name: 'В057 Информационные технологии', education_form_id: 1 },
    { name: 'В058 Информационная безопасность', education_form_id: 1 },
    { name: 'В059 Коммуникации и коммуникационные технологии', education_form_id: 1 },
    { name: 'В060 Химическая инженерия и процессы', education_form_id: 1 },
    { name: 'В061 Материаловедение и технологии', education_form_id: 1 },
    { name: 'В062 Электротехника и энергетика', education_form_id: 1 },
    { name: 'В063 Электротехника и автоматизация', education_form_id: 1 },
    { name: 'В064 Механика и металлообработка', education_form_id: 1 },
    { name: 'В065 Автотранспортные средства', education_form_id: 1 },
    { name: 'В071 Горное дело и добыча полезных ископаемых', education_form_id: 1 },
    { name: 'В073 Архитектура', education_form_id: 1 },
    { name: 'В074 Градостроительство, строительные работы и гражданское строительство', education_form_id: 1 },
    { name: 'В075 Кадастр и землеустройство', education_form_id: 1 },
    { name: 'В076 Стандартизация, сертификация и метрология (по отраслям)', education_form_id: 1 },
    { name: 'В094 Санитарно-профилактические мероприятия', education_form_id: 1 },
    { name: 'В095 Транспортные услуги', education_form_id: 1 },

    { name: 'В031 Мода, дизайн интерьера и промышленный дизайн', education_form_id: 2 },
    { name: 'В044 Менеджмент и управление', education_form_id: 2 },
    { name: 'В045 Аудит и налогообложение', education_form_id: 2 },
    { name: 'В046 Финансы, экономика, банковское и страховое дело', education_form_id: 2 },
    { name: 'В047 Маркетинг и реклама', education_form_id: 2 },
    { name: 'В050 Биологические и смежные науки', education_form_id: 2 },
    { name: 'В057 Информационные технологии', education_form_id: 2 },
    { name: 'В058 Информационная безопасность', education_form_id: 2 },
    { name: 'В059 Коммуникации и коммуникационные технологии', education_form_id: 2 },
    { name: 'В060 Химическая инженерия и процессы', education_form_id: 2 },
    { name: 'В061 Материаловедение и технологии', education_form_id: 2 },
    { name: 'В062 Электротехника и энергетика', education_form_id: 2 },
    { name: 'В162 Теплоэнергетика', education_form_id: 2 },
    { name: 'В063 Электротехника и автоматизация', education_form_id: 2 },
    { name: 'В064 Механика и металлообработка', education_form_id: 2 },
    { name: 'В065 Автотранспортные средства', education_form_id: 2 },
    { name: 'В071 Горное дело и добыча полезных ископаемых', education_form_id: 2 },
    { name: 'В171 Металлургия', education_form_id: 2 },
    { name: 'В271 Нефтегазовое дело', education_form_id: 2 },
    { name: 'В073 Архитектура', education_form_id: 2 },
    { name: 'В074 Градостроительство, строительные работы и гражданское строительство', education_form_id: 2 },
    { name: 'В076 Стандартизация, сертификация и метрология (по отраслям)', education_form_id: 2 },
    { name: 'В094 Санитарно-профилактические мероприятия', education_form_id: 2 },
    { name: 'В095 Транспортные услуги', education_form_id: 2 },
    
    # магистратура
    { name: '7М01401 Профессиональное обучение ( по отраслям)', education_form_id: 3 },
    { name: '7М04101 Экономика', education_form_id: 3 },
    { name: '7М04102 Стратегический менеджмент на горнодобывающих предприятиях', education_form_id: 3 },
    { name: '7М04103 Государственное и местное управление', education_form_id: 3 },
    { name: '7M06101 Информационные системы', education_form_id: 3 },
    { name: '7M06102 Вычислительная техника и программное обеспечение', education_form_id: 3 },
    { name: '7M07101 Автоматизация и управление', education_form_id: 3 },
    { name: '7M07102 Материаловедение и технология новых материалов', education_form_id: 3 },
    { name: '7М07103 Машиностроение', education_form_id: 3 },
    { name: '7M07104 Транспорт, транспортная техника и технологии', education_form_id: 3 },
    { name: '7М07105 Приборостроение', education_form_id: 3 },
    { name: '7М07106 Теплоэнергетика', education_form_id: 3 },
    { name: '7М07107 Электроэнергетика', education_form_id: 3 },
    { name: '7М07108 Химическая технология органических веществ', education_form_id: 3 },
    { name: '7М07109 Технологические машины и оборудование (по отраслям)', education_form_id: 3 },
    { name: '7M07201 Геофизические методы поисков и разведки месторождений полезных ископаемых', education_form_id: 3 },
    { name: '7M07202 Геология и разведка месторождений полезных ископаемых', education_form_id: 3 },
    { name: '7М07203 Горное дело', education_form_id: 3 },
    { name: '7M07204 Металлургия', education_form_id: 3 },
    { name: '7М07205 Маркшейдерское дело', education_form_id: 3 },
    { name: '7М07302 Строительство', education_form_id: 3 },
    { name: '7М07303 Производство строительных материалов, изделий и конструкций', education_form_id: 3 },
    { name: '7М07304 Картография', education_form_id: 3 },
    { name: '7M07301 Геодезия', education_form_id: 3 },
    { name: '7М07305 Дистанционное зондирование земли ', education_form_id: 3 },
    { name: '7М07501 Стандартизация, сертификация и метрология (по отраслям)', education_form_id: 3 },
    { name: '7М07502 Метрология', education_form_id: 3 },
    { name: '7M11201 Безопасность жизнедеятельности и защита окружающей среды', education_form_id: 3 },
    { name: '7М11301 Организация перевозок, движения и эксплуатация транспорта', education_form_id: 3 },

    # докторантура
    { name: '8D07101 Машиностроение', education_form_id: 4 },
    { name: '8D07102 Транспорт, транспортная техника и технологии', education_form_id: 4 },
    { name: '8D07103 Электроэнергетика', education_form_id: 4 },
    { name: '8D07201 Геология и разведка месторождений полезных ископаемых', education_form_id: 4 },
    { name: '8D07202 Горное дело', education_form_id: 4 },
    { name: '8D07203 Металлургия', education_form_id: 4 },
    { name: '8D07301 Строительство', education_form_id: 4 },
    { name: '8D07302 Производство строительных материалов, изделий и конструкций', education_form_id: 4 },

    # второе высшее
    { name: 'В004 Подготовка учителей начальной военной подготовки', education_form_id: 5 },
    { name: 'В007 Подготовка учителей художественного труда и черчения', education_form_id: 5 },
    { name: 'В031 Мода, дизайн интерьера и промышленный дизайн', education_form_id: 5 },
    { name: 'В044 Менеджмент и управление', education_form_id: 5 },
    { name: 'В045 Аудит и налогообложение', education_form_id: 5 },
    { name: 'В046 Финансы, экономика, банковское и страховое дело', education_form_id: 5 },
    { name: 'В047 Маркетинг и реклама', education_form_id: 5 },
    { name: 'В057 Информационные технологии', education_form_id: 5 },
    { name: 'В059 Коммуникации и коммуникационные технологии', education_form_id: 5 },
    { name: 'В060 Химическая инженерия и процессы', education_form_id: 5 },
    { name: 'В061 Материаловедение и технологии', education_form_id: 5 },
    { name: 'В062 Электротехника и энергетика', education_form_id: 5 },
    { name: 'В063 Электротехника и автоматизация', education_form_id: 5 },
    { name: 'В064 Механика и металлообработка', education_form_id: 5 },
    { name: 'В065 Автотранспортные средства', education_form_id: 5 },
    { name: 'В071 Горное дело и добыча полезных ископаемых', education_form_id: 5 },
    { name: 'В073 Архитектура', education_form_id: 5 },
    { name: 'В074 Градостроительство, строительные работы и гражданское строительство', education_form_id: 5 },
    { name: 'В075 Кадастр и землеустройство', education_form_id: 5 },
    { name: 'В076 Стандартизация, сертификация и метрология (по отраслям)', education_form_id: 5 },
    { name: 'В094 Санитарно-профилактические мероприятия', education_form_id: 5 },
    { name: 'В095 Транспортные услуги', education_form_id: 5 },
])

InstitutionType.create([
    { name: 'школа' },
    { name: 'колледж' },
    { name: 'университет (бакалавриат/магистратура)' },
    { name: 'другое' },
])

Subject.create([
    # школа
    { name: 'Математика/Физика', institution_type_id: 1 },
    { name: 'Математика/География', institution_type_id: 1 },
    { name: 'Биология/Химия', institution_type_id: 1 },
    { name: 'Химия/Физика', institution_type_id: 1 },
    { name: 'Творческий экзамен', institution_type_id: 1 },

    { name: 'другой профильный предмет', institution_type_id: 4 },
])

Institution.create([
    # другое
    { name: 'другое учебное заведение', institution_type_id: 4, city_id: 2 },
    
    # университеты
    { name: 'Карагандинский технический университет', institution_type_id: 3, city_id: 2 },
    { name: 'Карагандинский университет', institution_type_id: 3, city_id: 2 },
    { name: 'Академия Болашак', institution_type_id: 3, city_id: 2 },
    { name: 'Карагандинский экономический университет', institution_type_id: 3, city_id: 2 },

    # Караганды
    { name: 'СШ №12', institution_type_id: 1, city_id: 2 },
    { name: 'Технический лицей №2', institution_type_id: 1, city_id: 2 },
    { name: 'ШГ №95 г. Караганды', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ №6', institution_type_id: 1, city_id: 2 },
    { name: 'СШ№ 23', institution_type_id: 1, city_id: 2 },
    { name: 'СШ №15', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ ОСШ №16', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ Гимназия №93', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СШ №41', institution_type_id: 1, city_id: 2 },
    { name: '№4 ЖББОМ', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия №39 им.М.Жумабаева', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ «СОШ № 52', institution_type_id: 1, city_id: 2 },
    { name: 'Школа-лицей им. С.Саттарова', institution_type_id: 1, city_id: 2 },
    { name: 'СШ№33', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия №38', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ №74', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ № 48', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ № 58', institution_type_id: 1, city_id: 2 },
    { name: 'KГУ ОСШ №27', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия №9', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ №88', institution_type_id: 1, city_id: 2 },
    { name: 'СШ 83', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ №8', institution_type_id: 1, city_id: 2 },
    { name: 'ШЛ №103', institution_type_id: 1, city_id: 2 },
    { name: 'ОСШ №66', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ №30', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия №3', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ №86', institution_type_id: 1, city_id: 2 },
    { name: 'ОСШ № 82', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ-Л №53', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия № 45', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ СОШ № 62', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ СОШ №91', institution_type_id: 1, city_id: 2 },
    { name: '№18 ЖББМ', institution_type_id: 1, city_id: 2 },
    { name: 'ШЦДО №5', institution_type_id: 1, city_id: 2 },
    { name: 'СШ 32', institution_type_id: 1, city_id: 2 },
    { name: 'СШ 54', institution_type_id: 1, city_id: 2 },
    { name: 'СШ 36', institution_type_id: 1, city_id: 2 },
    { name: 'ОСШ 25', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ СОШ школа №59', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ № 100', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ ОСШ № 65', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ №63', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ № 85', institution_type_id: 1, city_id: 2 },
    { name: '№68 МИББ кешені', institution_type_id: 1, city_id: 2 },
    { name: 'ШГ №102', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ №10', institution_type_id: 1, city_id: 2 },
    { name: 'ОСШ№61', institution_type_id: 1, city_id: 2 },
    { name: 'школа №101', institution_type_id: 1, city_id: 2 },
    { name: 'ОКШДС №77', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ №76 им.А.Букейхана', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ Гимназия № 1', institution_type_id: 1, city_id: 2 },
    { name: 'ГУ СШ №35 имени Ю.Н. Павлова', institution_type_id: 1, city_id: 2 },
    { name: 'СШ 46', institution_type_id: 1, city_id: 2 },
    { name: 'СШ-17', institution_type_id: 1, city_id: 2 },
    { name: 'Гимназия 97', institution_type_id: 1, city_id: 2 },
    { name: 'СОШ № 81', institution_type_id: 1, city_id: 2 },
    { name: 'КГУ Гимназия №92', institution_type_id: 1, city_id: 2 },
    { name: '«БІЛІМ-ИННОВАЦИЯ» лицей-интернат №2', institution_type_id: 1, city_id: 2},
    { name: 'ОСШИ для одаренных детей  №7 им.Жамбыла  ', institution_type_id: 1, city_id: 2},
    { name: 'СШЛИ Информационных технологий', institution_type_id: 1, city_id: 2},
    { name: 'КГУ Зияткер', institution_type_id: 1, city_id: 2},
    { name: 'СШОД имени Н.Нурмакова', institution_type_id: 1, city_id: 2},
    { name: 'ГУ СШИ  для одаренных детей Дарын', institution_type_id: 1, city_id: 2},
    { name: 'Литвинская школа-интернат для детей сирот и детей оставшихся без попечения родителей', institution_type_id: 1, city_id: 2},
    { name: 'Мурагер', institution_type_id: 1, city_id: 2},
    { name: 'Специализированная музыкальная школа интернат', institution_type_id: 1, city_id: 2},
    { name: 'ОСШИ в спорте детей имени Алии Молдагуловой', institution_type_id: 1, city_id: 2},

    # Абайский
    { name: '№15 п.Карабас', institution_type_id: 1, city_id: 12 },
    { name: 'СШ №5 им.Кунанбаева', institution_type_id: 1, city_id: 1 },
    { name: 'Акбастауская ОШ', institution_type_id: 1, city_id: 12 },
    { name: 'ОШ № 4', institution_type_id: 1, city_id: 12 },
    { name: 'Топарская ОШ', institution_type_id: 1, city_id: 12 },
    { name: 'СШ № 1', institution_type_id: 1, city_id: 1 },
    { name: 'СШ №12', institution_type_id: 1, city_id: 1 },
    { name: 'СШ им.Абая', institution_type_id: 1, city_id: 1 },
    { name: 'СШ №14', institution_type_id: 1, city_id: 1 },
    { name: 'Есенгельдинская ОШ', institution_type_id: 1, city_id: 12 },
    { name: 'СШ им.Корниенко', institution_type_id: 1, city_id: 12 },
    { name: 'ГУ Дубовская ОСШ', institution_type_id: 1, city_id: 12 },
    { name: 'Коксунская с.Коксу', institution_type_id: 1, city_id: 12 },
    { name: 'СШ-гимназия №10', institution_type_id: 1, city_id: 10 },
    { name: 'СШ им. Момышулы', institution_type_id: 1, city_id: 12 },
    { name: 'Дзержинская ОШ', institution_type_id: 1, city_id: 12 },
    { name: 'Мерей с. Юбилейное', institution_type_id: 1, city_id: 12 },
    { name: '№9 п. Южный', institution_type_id: 1, city_id: 12 },
    { name: 'Жулдыз с. Жартас', institution_type_id: 1, city_id: 12 },
    { name: 'Самарская ОШ', institution_type_id: 1, city_id: 12 },
    { name: 'Курминская с. Курма', institution_type_id: 1, city_id: 12 },

    # Актогайский
    { name: 'КГУ ОСШ пос.Сарышаган', institution_type_id: 1, city_id: 11 },
    { name: 'СШ с.Кызыларай', institution_type_id: 1, city_id: 11 },
    { name: 'СШ им. Алимхана Ермекова', institution_type_id: 1, city_id: 11 },
    { name: 'СШ им. Жабас Кенесбаева', institution_type_id: 1, city_id: 11 },
    { name: 'Ортадересинская', institution_type_id: 1, city_id: 11 },
    { name: 'Қошқар ЖББМ ', institution_type_id: 1, city_id: 11 },
    { name: 'СШ им. Казбека Нуржанова', institution_type_id: 1, city_id: 11 },
    { name: 'им М.Ержанова', institution_type_id: 1, city_id: 11 },
    { name: 'Тасаральская', institution_type_id: 1, city_id: 11 },
    { name: 'СШ им. Нуркена Абдирова', institution_type_id: 1, city_id: 11 },
    { name: 'КГУ «ОСШ им.К.Байсейтова»', institution_type_id: 1, city_id: 11 },
    { name: 'СШ Шашубай', institution_type_id: 1, city_id: 11 },

    # Балхаш
    { name: 'КГУ «ШЛ № 17 »', institution_type_id: 1, city_id: 7 },
    { name: 'СШ №10', institution_type_id: 1, city_id: 7 },
    { name: 'ОСШ  №6 поселка Сая', institution_type_id: 1, city_id: 7 },
    { name: 'СШ №24', institution_type_id: 1, city_id: 7 },
    { name: 'КГУ СШ № 4 имени Н. К. Крупской', institution_type_id: 1, city_id: 7 },
    { name: 'ШГ №7 им.С.Сейфуллина', institution_type_id: 1, city_id: 7 },
    { name: 'КГУ ОСШ  №9', institution_type_id: 1, city_id: 7 },
    { name: 'КГУ Школа-лицей №15', institution_type_id: 1, city_id: 7 },
    { name: 'СШ №5 ', institution_type_id: 1, city_id: 7 },
    { name: 'КГУ ОСШ №3 поселка Конырат', institution_type_id: 1, city_id: 7 },
    { name: 'СШ №25 им. Ы. Алтынсарина', institution_type_id: 1, city_id: 7 },
    { name: 'КГУ «ОСШ  №1 города Балхаш»', institution_type_id: 1, city_id: 7 },
    { name: 'СШИ №2 имени М.П.Русакова', institution_type_id: 1, city_id: 7 },
    { name: '№16 ОМ', institution_type_id: 1, city_id: 7 },
    { name: '№2 имени Абая', institution_type_id: 1, city_id: 7 },
    { name: 'СШ №8', institution_type_id: 1, city_id: 7 },

    # Бухар-Жырауский
    { name: 'Зареченская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Токаревская СОШ ', institution_type_id: 1, city_id: 13 },
    { name: 'Ленинская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'Новоузенская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Нуринская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'Мәнжі батыр атындағы Қаражар орта мектебі', institution_type_id: 1, city_id: 13 },
    { name: 'Центральная средняя школа', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Березняковская средняя школа', institution_type_id: 1, city_id: 13 },
    { name: '№1 қазақ орта мектебі ММ', institution_type_id: 1, city_id: 13 },
    { name: 'Умуткерская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'Амангельдинская СШ', institution_type_id: 1, city_id: 13 },
    { name: 'СШ Туздинская ', institution_type_id: 1, city_id: 13 },
    { name: 'Актюбинская СШ', institution_type_id: 1, city_id: 13 },
    { name: 'Сартауская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Уштобинская СШ', institution_type_id: 1, city_id: 13 },
    { name: 'ОСШ имени Ю.Гагарина', institution_type_id: 1, city_id: 13 },
    { name: 'Кокпектинская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Ростовская ОСШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Кушокинская ОСШ', institution_type_id: 1, city_id: 13 },
    { name: 'Акоринская средняя школа', institution_type_id: 1, city_id: 13 },
    { name: 'Кузнецкая СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Петровская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Ельтайская ОСШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Шешенкаринская ОСШ', institution_type_id: 1, city_id: 13 },
    { name: 'ГУ Ботакаринская СОШ', institution_type_id: 1, city_id: 13 },
    { name: 'СШ им.К.Сатбаева', institution_type_id: 1, city_id: 13 },
    { name: 'Калининская ОСШ', institution_type_id: 1, city_id: 13 },
    { name: 'Байкадамская СШ', institution_type_id: 1, city_id: 13 },
    { name: 'Кернеевская ОСШ', institution_type_id: 1, city_id: 13 },

    # Жанааркинский
    { name: 'СОШ Ынтымак', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Актюбекская ', institution_type_id: 1, city_id: 14 },
    { name: 'СШ им. Гагарина', institution_type_id: 1, city_id: 14 },
    { name: 'Жанааркинская СОШ', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Жумабекова', institution_type_id: 1, city_id: 14 },
    { name: 'СШ им. С.Сейфуллина', institution_type_id: 1, city_id: 14 },
    { name: 'ОСШ имени Амалбекова Б.', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Бидаикская ', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Ынталы', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Талдыбулакская ', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Коктальская ', institution_type_id: 1, city_id: 14 },
    { name: 'СШ №132', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Кызылжар', institution_type_id: 1, city_id: 14 },
    { name: 'СШ им.О.Алибаева', institution_type_id: 1, city_id: 14 },
    { name: 'СШ Атасуйская ', institution_type_id: 1, city_id: 14 },
    { name: 'СОШ имени Ж.Садвакасова', institution_type_id: 1, city_id: 14 },

    # Жезказган
    { name: 'СШ13', institution_type_id: 1, city_id: 8 },
    { name: '№21 орта мектебі', institution_type_id: 1, city_id: 8 },
    { name: 'СОШ №4', institution_type_id: 1, city_id: 8 },
    { name: 'КММ ОСШ №1', institution_type_id: 1, city_id: 8 },
    { name: 'ГУ СШ №10', institution_type_id: 1, city_id: 8 },
    { name: 'ГУ гимназия №26', institution_type_id: 1, city_id: 8 },
    { name: 'Гимназия №8', institution_type_id: 1, city_id: 8 },
    { name: 'СОШ №9', institution_type_id: 1, city_id: 8 },
    { name: 'Вечерняя ОШ', institution_type_id: 1, city_id: 8 },
    { name: 'ОСШ №11', institution_type_id: 1, city_id: 8 },
    { name: 'ГУ СОШ №24', institution_type_id: 1, city_id: 8 },
    { name: 'ШЛ №7', institution_type_id: 1, city_id: 8 },
    { name: '№5 орта мектеп', institution_type_id: 1, city_id: 8 },
    { name: 'Средняя школа №22', institution_type_id: 1, city_id: 8 },
    { name: 'средняя школа №3', institution_type_id: 1, city_id: 8 },
    { name: 'СШ №2 Кенгир', institution_type_id: 1, city_id: 8 },

    # Каражал
    { name: 'СШ №1', institution_type_id: 1, city_id: 15 },
    { name: 'СШ №3', institution_type_id: 1, city_id: 15 },
    { name: 'СШ №7', institution_type_id: 1, city_id: 15 },
    { name: 'СШ №10', institution_type_id: 1, city_id: 15 },
    { name: 'СШ №30', institution_type_id: 1, city_id: 15 },
    { name: 'СШ №5', institution_type_id: 1, city_id: 15 },

    # Каркаралинский
    { name: '№18 СОШ', institution_type_id: 1, city_id: 17 },
    { name: 'КГУ СОШ №31', institution_type_id: 1, city_id: 17 },
    { name: 'СШ №22 села Томар', institution_type_id: 1, city_id: 17 },
    { name: 'СШ №43', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ №32 с.Актасты', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ №1 им.Академика О.А.Жаутыкова', institution_type_id: 1, city_id: 17 },
    { name: '№23 СОШ с.Татан', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ имени Н. Абдирова №10 с. Жарлы', institution_type_id: 1, city_id: 17 },
    { name: '№14 СОШ села Жанатоган', institution_type_id: 1, city_id: 17 },
    { name: '№5 СОШ Егиндыбулак', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ №3 с.Ынталы', institution_type_id: 1, city_id: 17 },
    { name: '№20 СОШ села Буркитты', institution_type_id: 1, city_id: 17 },
    { name: 'Әлібек Бүркітбаев атындағы ЖББ №12 орта мектебі', institution_type_id: 1, city_id: 17 },
    { name: 'ОСШ №35', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ №8 села Бесоба', institution_type_id: 1, city_id: 17 },
    { name: '№44 школа им.Мади Бапиулы', institution_type_id: 1, city_id: 17 },
    { name: '№15', institution_type_id: 1, city_id: 17 },
    { name: 'СШ №16', institution_type_id: 1, city_id: 17 },
    { name: 'СШ №4', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ № 21села', institution_type_id: 1, city_id: 17 },
    { name: 'СОШ №2', institution_type_id: 1, city_id: 17 },
    { name: '№19 школа', institution_type_id: 1, city_id: 17 },
    { name: '№17 школа', institution_type_id: 1, city_id: 17 },

    # Нуринский
    { name: 'Шубаркульской ОШ им. Абая', institution_type_id: 1, city_id: 16 },
    { name: 'ОШ им.К.Шайменова', institution_type_id: 1, city_id: 16 },
    { name: 'СШ №2', institution_type_id: 1, city_id: 16 },
    { name: 'Жараспайская ОШ', institution_type_id: 1, city_id: 16 },
    { name: 'ОШ им.С.О.Талжанова', institution_type_id: 1, city_id: 16 },
    { name: 'Каройская СОШ', institution_type_id: 1, city_id: 16 },
    { name: 'Каракойынская СОШ', institution_type_id: 1, city_id: 16 },
    { name: 'СОШ им.Рахим Асубаева', institution_type_id: 1, city_id: 16 },
    { name: 'ОСШ Абдоллы Асылбекова', institution_type_id: 1, city_id: 16 },
    { name: 'СШ №1', institution_type_id: 1, city_id: 16 },
    { name: 'СШ №3', institution_type_id: 1, city_id: 16 },
    { name: 'Нуринская ОСШ', institution_type_id: 1, city_id: 16 },
    { name: 'Заречная ОШ', institution_type_id: 1, city_id: 16 },
    { name: 'СОШ им.Сакена Сейфуллина', institution_type_id: 1, city_id: 16 },
    { name: 'СОШ им.М.Сулейменова', institution_type_id: 1, city_id: 16 },
    { name: 'Баршинская СОШ', institution_type_id: 1, city_id: 16 },
    { name: 'Индустриальная ОШ', institution_type_id: 1, city_id: 16 },
    { name: 'Щербаковская СОШ', institution_type_id: 1, city_id: 16 },
    { name: 'Пржеваль СОШ', institution_type_id: 1, city_id: 16 },

    # Осакаровский
    { name: '№ 1 средняя школа', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №22 села Тельманское', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №28 села Акбулак', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №29 села Сенакосное', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №25 села Родниковское', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №7 села Приишимское ', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №20 села Мирное', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №6 с.Батпак', institution_type_id: 1, city_id: 18 },
    { name: '№8 школа села Уызбай', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №17 села Сункар', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №24 села Дальнее', institution_type_id: 1, city_id: 18 },
    { name: 'КГУ Опорная школа  гимназии №9 ', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №15 села Трудовое', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №11 села Шункыркол', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №16 села Садовое', institution_type_id: 1, city_id: 18 },
    { name: 'СШ № 3 села Пионерское', institution_type_id: 1, city_id: 18 },
    { name: '№13 школа села Озерное', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №5 села Карагайлы', institution_type_id: 1, city_id: 18 },
    { name: '№21 средняя школа', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №26 ', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №2 с.Есиль', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №10 села Николаевка', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №23 школа ', institution_type_id: 1, city_id: 18 },
    { name: 'Средняя школа №18 села Звездное', institution_type_id: 1, city_id: 18 },
    { name: 'СШ №12 ', institution_type_id: 1, city_id: 18 },

    # Приозерск
    { name: 'СШ №2', institution_type_id: 1, city_id: 6 },
    { name: 'СШ №1', institution_type_id: 1, city_id: 6 },

    # Сарань
    { name: 'КГУ СОШ №1', institution_type_id: 1, city_id: 4 },
    { name: 'СШ№ 7', institution_type_id: 1, city_id: 4 },
    { name: 'ОШ №4 ', institution_type_id: 1, city_id: 4 },
    { name: 'КГУ СОШ№13', institution_type_id: 1, city_id: 4 },
    { name: 'СШ№ 16', institution_type_id: 1, city_id: 4 },
    { name: 'СШ №17', institution_type_id: 1, city_id: 4 },
    { name: 'СШ №6', institution_type_id: 1, city_id: 4 },

    # Сатпаев
    { name: 'ОШ №15', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ СШ №16', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ СШ №7', institution_type_id: 1, city_id: 9 },
    { name: 'СШ №5', institution_type_id: 1, city_id: 9 },
    { name: 'КГУ СШ №14', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ Гимназия имени Сакена Сейфуллина', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ СШ №19', institution_type_id: 1, city_id: 9 },
    { name: 'ШЛ №4', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ СШ №25', institution_type_id: 1, city_id: 9 },
    { name: 'ГУ ШГ №1 г.Сатпаев', institution_type_id: 1, city_id: 9 },
    { name: 'КГУ СОШ №27', institution_type_id: 1, city_id: 9 },

    # Темиртау
    { name: 'СШ №27 ', institution_type_id: 1, city_id: 5 },
    { name: 'СШ-гимназия №15', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №16', institution_type_id: 1, city_id: 5 },
    { name: 'КГУОСШ №24', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №23', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №32', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №10', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №19', institution_type_id: 1, city_id: 5 },
    { name: 'СШ-лицей №9', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №3', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №7', institution_type_id: 1, city_id: 5 },
    { name: 'лицей №20 ', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №28', institution_type_id: 1, city_id: 5 },
    { name: 'СОШ №2', institution_type_id: 1, city_id: 5 },
    { name: 'женская гимназия ', institution_type_id: 1, city_id: 5 },
    { name: 'КГУ ОСШ №4', institution_type_id: 1, city_id: 5 },
    { name: 'СОШ №6', institution_type_id: 1, city_id: 5 },
    { name: 'гимназия им.Т.Аубакирова', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №14', institution_type_id: 1, city_id: 5 },
    { name: 'СШ 29', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №8', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №17', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №21', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №1', institution_type_id: 1, city_id: 5 },
    { name: 'СШ №31 ', institution_type_id: 1, city_id: 5 },
    { name: 'КГУКСШ №5', institution_type_id: 1, city_id: 5 },
    { name: 'Первый Темиртауский классический Лицей', institution_type_id: 1, city_id: 5 },
    { name: 'ГУ Гимназия №1', institution_type_id: 1, city_id: 5 },

    # Улытауский
    { name: 'СШ№14 Алгабасская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №7 Сарысуская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ№18 Мибулакская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ№2 Коргасынская', institution_type_id: 1, city_id: 10 },
    { name: 'ОСШ   Жезды', institution_type_id: 1, city_id: 10 },
    { name: 'СШ№3 Амангельдинская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №10 Борсенгирская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ№11 Коскольская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №8 Егиндинская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №1', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №6 Жездинская', institution_type_id: 1, city_id: 10 },
    { name: 'Школа №17 Байконур', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №15 им.Ж.Жабаева', institution_type_id: 1, city_id: 10 },
    { name: 'СШ№9 Терсакканская', institution_type_id: 1, city_id: 10 },
    { name: 'СШ №4 Каракенгирская', institution_type_id: 1, city_id: 10 },

    # Шахтинск
    { name: 'КГУ ШЛ имени А.Бокейханова', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ  №1', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №6', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №12', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ Гимназия №5 акимата', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №11', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №2', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №7', institution_type_id: 1, city_id: 3 },
    { name: 'КГУ ОШ №3', institution_type_id: 1, city_id: 3 },

    # Шетский
    { name: 'СШ им.Хасена Саринжипулы', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ Сакена', institution_type_id: 1, city_id: 19 },
    { name: 'СШ им.Гагарина', institution_type_id: 1, city_id: 19 },
    { name: 'Ы.Алтынсарин ', institution_type_id: 1, city_id: 19 },
    { name: 'Нураталдинская ОШ', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ имени Ш.Батталовой', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ имени Абая', institution_type_id: 1, city_id: 19 },
    { name: 'гимназия имени Ж.Акылбаева', institution_type_id: 1, city_id: 19 },
    { name: 'Жарыкская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ Бурминская', institution_type_id: 1, city_id: 19 },
    { name: 'Талдинская СШ', institution_type_id: 1, city_id: 19 },
    { name: 'Шетская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ Дарьинская', institution_type_id: 1, city_id: 19 },
    { name: 'Красно-полянская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'Акойская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ имени Ш.Уалиханова', institution_type_id: 1, city_id: 19 },
    { name: 'Батыкская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'Кызылкойская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'Коктенкольская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'Еркиндикская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ имени А.Ермекова', institution_type_id: 1, city_id: 19 },
    { name: 'Нуринская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'СШ им.Маметова', institution_type_id: 1, city_id: 19 },
    { name: 'ОСШ имени С.Мукамеджанова', institution_type_id: 1, city_id: 19 },
    { name: 'Босагинская ОСШ', institution_type_id: 1, city_id: 19 },
    { name: 'Мойынтинская ОСШ', institution_type_id: 1, city_id: 19 },

    # Караганды - колледжи
    { name: 'Карагандинский банковский колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский профессионально-технический колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский горно-индустриальный колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский железнодорожный колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский технико-строительный колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский гуманитарный колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский колледж моды', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский агротехнический колледж', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский транспортно-технологический колледж', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский машиностроительный колледж', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский Медицинский Интерколледж', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский Областной Высший Сестринский Колледж', institution_type_id: 2, city_id: 2},
    { name: 'Медицинский колледж при Карагандинском медицинском университет', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский медико-технический колледж', institution_type_id: 2, city_id: 2},
    { name: 'Карагандинский колледж актуального образования «Болашак»', institution_type_id: 2, city_id: 2},
    { name: 'Медицинский колледж при Карагандинском медицинском университете', institution_type_id: 2, city_id: 2},
    { name: 'Колледж «Международная Бизнес-Академия»  ', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский профессионально-технический колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Многопрофильный гуманитарно-технический колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский коммерческий колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский колледж экономики и статистики', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский коммерческий колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский технико-строительный колледж', institution_type_id: 2, city_id: 2 },
    { name: 'Карагандинский агротехнический колледж', institution_type_id: 2, city_id: 2 },

    # Сатпаев
    { name: 'Технологический колледж корпорации «Казахмыс»', institution_type_id: 2, city_id: 9 },
    { name: 'Сатпаевский индустриальный колледж', institution_type_id: 2, city_id: 9 },

    # Каркаралинский
    { name: 'Егиндыбулакский агротехнический колледж', institution_type_id: 2, city_id: 17 },
    { name: 'Каркаралинский многопрофильный колледж', institution_type_id: 2, city_id: 17 },
    { name: 'Каркаралинский сельскохозяйственный колледж имени Мынжасара Адекенова', institution_type_id: 2, city_id: 17 },
    
    # Жезказган
    { name: 'Жезказганский колледж технологии и сервиса', institution_type_id: 2, city_id: 8 },
    { name: 'Жезказганский гуманитарный колледж', institution_type_id: 2, city_id: 8 },
    { name: 'Медицинский колледж города Жезказган', institution_type_id: 2, city_id: 8 },
    { name: 'Жезказганский политехнический колледж, 2', institution_type_id: 2, city_id: 8},
    { name: 'Жезказганский индустриально-гуманитарный колледж', institution_type_id: 2, city_id: 8},
    { name: 'Жезказганский колледж Бизнеса и транспорта ', institution_type_id: 2, city_id: 8},

    # Балхаш
    { name: 'Балхашский  многопрофильный колледж, 2.', institution_type_id: 2, city_id: 7 },
    { name: 'Балхашский колледж актуального образования академика Ж.С. Акылбаева', institution_type_id: 2, city_id: 7 },
    { name: 'Балхашский технический колледж имени "Халық қаһарманы РК" Р.Кошкарбаева', institution_type_id: 2, city_id: 7 },              
    { name: 'Балхашский гуманитарно-технический колледж', institution_type_id: 2, city_id: 7 },              
    { name: 'Политехнический колледж корпорации "Казахмыс" в Балхаше', institution_type_id: 2, city_id: 7 },

    # Улытауский
    { name: 'Карсакпайский агротехнический колледж', institution_type_id: 2, city_id: 10 },
    
    # Темиртау
    { name: 'Темиртауский индустриально-технологический колледж', institution_type_id: 2, city_id: 5 },
    { name: 'Темиртауский высший политехнический колледж', institution_type_id: 2, city_id: 5 },
    { name: 'Темиртауский профессионально-технический колледж', institution_type_id: 2, city_id: 5 },
    { name: 'Темиртауский политехнический колледж', institution_type_id: 2, city_id: 5 },
    { name: 'Темиртауский высший медицинский колледж.', institution_type_id: 2, city_id: 5 },
    { name: 'Темиртауский технологический колледж ', institution_type_id: 2, city_id: 5 },
    
    # Шахтинск
    { name: 'Шахтинский технологический колледж', institution_type_id: 2, city_id: 3 },
    
    # Абайский
    { name: 'Мичуринский аграрно-технический колледж (нынешний Абайский многопрофильный колледж)', institution_type_id: 2, city_id: 12 },
    
    # Бухар-Жырауский
    { name: 'Бухар-Жырауский агротехнический колледж', institution_type_id: 2, city_id: 13 },
    
    # Нуринский
    { name: 'Нуринский многопрофильный колледж', institution_type_id: 2, city_id: 16 },
    
    # Шетский
    { name: 'Шетский агротехнический колледж', institution_type_id: 2, city_id: 19 },
    
    # Каражал
    { name: 'Каражалский горно-технический колледж', institution_type_id: 2, city_id: 15 },
    
    # Актогайский
    { name: 'Актогайский аграрно-технический колледж', institution_type_id: 2, city_id: 11 },
    
    # Сарань
    { name: 'Саранский гуманитарно-технический колледж им. Абая Кунанбаева', institution_type_id: 2, city_id: 4 },
    { name: 'Саранский технический колледж', institution_type_id: 2, city_id: 4 },
])
